spring:
  application:
    name: lotto-pos-manager

server:
  port: ${POS_MANAGER_PORT}

central:
  server:
    url: ${CENTRAL_SERVER_URL}

logging:
  level:
    root: INFO
    org.woonyong.lotto: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
