spring:
  application:
    name: lotto-pos-manager

central:
  server:
    url: ${CENTRAL_SERVER_URL}

pos:
  manager:
    max-terminal-capacity: ${POS_MANAGER_MAX_TERMINAL_CAPACITY}
    health-check-interval-ms: ${POS_MANAGER_HEALTH_CHECK_INTERVAL_MS}
    read-timeout: ${POS_MANAGER_READ_TIMEOUT}
    sse-interval-ms: ${SSE_UPDATE_INTERVAL}
    dashboard-url: ${DASHBOARD_URL}

server:
  port: ${POS_MANAGER_PORT}

logging:
  level:
    root: INFO
    org.woonyong.lotto: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
