spring:
  application:
    name: lotto-central-server

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true

lotto:
  round:
    open-duration: ${LOTTO_ROUND_OPEN_DURATION}
    closed-duration: ${LOTTO_ROUND_CLOSED_DURATION}
    check-interval: ${LOTTO_ROUND_CHECK_INTERVAL}
    sse-interval: 500

server:
  port: ${CENTRAL_SERVER_PORT}

logging:
  level:
    root: INFO
    org.woonyong.lotto: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
